Core v0.11
membraneframework/membrane_webrtc_plugin pull request #102
Opened 2022-12-19 12:50 UTC by mat-hek

2022-12-20 10:53 UTC, mickel8 requested changes

2022-12-20 10:53 UTC, mickel8 commented on lib/membrane_webrtc_plugin/endpoint_bin.ex
> +          raise "Unsupported"
?

2022-12-20 10:53 UTC, mickel8 commented on mix.exs
> +      {:membrane_rtp_plugin, github: "membraneframework/membrane_rtp_plugin", override: true},
Could we release this at first?

2022-12-20 10:53 UTC, mickel8 commented on mix.exs
> +      # {:opentelemetry, "~> 1.0.4"}
Looks like you forgot to uncomment

2022-12-20 10:53 UTC, mickel8 commented on lib/membrane_webrtc_plugin/endpoint_bin.ex
> +    # {[notify_child: {:ice, {:set_remote_candidate, candidate, 1}}], state}
I believe that the candidate should be passed to ice and ignored there if it's not needed

2022-12-20 12:15 UTC, daniel-jodlos commented
I don't think I'm qualified to do a review of this plugin.

2022-12-23 16:00 UTC, mat-hek commented on lib/membrane_webrtc_plugin/endpoint_bin.ex
> +    # {[notify_child: {:ice, {:set_remote_candidate, candidate, 1}}], state}
Hmm, can we move that to a separate task? It seems these notifications in ICE should be cleaned up - for example, the WebRTC plugin handles `candidate_gathering_done` which is never sent and ICE claims it handles `peer_candidate_gathering_done` which is not true...

2022-12-23 16:28 UTC, mickel8 commented on lib/membrane_webrtc_plugin/endpoint_bin.ex
> +    # {[notify_child: {:ice, {:set_remote_candidate, candidate, 1}}], state}
Sure

2022-12-23 16:42 UTC, mickel8 approved these changes

2022-12-23 16:58 UTC, merged