Msid in tracks
membraneframework/membrane_webrtc_plugin pull request #18
Opened 2021-04-27 13:18 UTC by FelonEkonom

2021-04-29 06:21 UTC, Qizot requested changes

2021-04-29 06:21 UTC, Qizot commented on lib/membrane_webrtc_plugin/endpoint.ex
> +  def update_tracks_ids(endpoint, mid_to_id) do
`mid_to_id` could as well be a tuple as it has just one element

2021-04-29 06:21 UTC, Qizot commented on lib/membrane_webrtc_plugin/endpoint.ex
> +      |> Map.new(&{&1.id, &1})
If you decided to change `mid_to_id` to a tuple `{mid, track_id}` this could look like this:
```suggestion
      |> Enum.map(fn 
        %Track{mid: ^mid} = track ->
            %Track{track | id: track_id}
        track ->
            track
      end)
      |> Map.new(&{&1.id, &1})
```

2021-04-29 11:25 UTC, mickel8 requested changes

2021-04-29 11:25 UTC, mickel8 commented on lib/membrane_webrtc_plugin/endpoint_bin.ex
> +      |> Enum.into(%{})
Use `Map.new` instead of `Enum.map` + `Enum.into`

2021-04-29 11:25 UTC, mickel8 commented on lib/membrane_webrtc_plugin/endpoint_bin.ex
> +      })
```suggestion
    state =
      Map.merge(state, %{
        inbound_tracks: inbound_tracks,
        mid_to_msid_app_data: mid_to_msid_app_data,
        ssrc_to_mid: ssrc_to_mid,
        first_sdp_answer_arrived?: true
      })
```

2021-04-29 11:25 UTC, mickel8 commented on lib/membrane_webrtc_plugin/endpoint_bin.ex
> +     state}
```suggestion
    actions = [forward: {:ice, {:set_remote_credentials, remote_credentials}}] ++ optional_notify_msg
    {{:ok, actions}, state}
```

2021-04-29 11:25 UTC, mickel8 commented on lib/membrane_webrtc_plugin/endpoint_bin.ex
> +
the version above is more concise I would leave it as it takes only one line

2021-04-29 11:25 UTC, mickel8 commented on lib/membrane_webrtc_plugin/endpoint_bin.ex
> +      end)
We should do this only for first sdp answer. We can create two clauses for `:sdp_answer` notification:
```elixir
def handle_other({:signal, {:sdp_answer, sdp}}, _ctx, %{first_sdp_answer_arrived?: false) do
  # update track ids, notify pipeline etc.
end

def handle_other({:signal, {:sdp_answer, sdp}}, _ctx, state) do
  # don't update track ids, notify pipeline etc.
end
 ```

2021-04-29 11:25 UTC, mickel8 commented on lib/membrane_webrtc_plugin/endpoint.ex
> +  def update_tracks_ids(endpoint, mid_to_id) do
I think it will in most cases include two keys one for audio and one for video

2021-04-29 11:25 UTC, mickel8 commented on lib/membrane_webrtc_plugin/endpoint.ex
> +      |> Map.new(&{&1.id, &1})
Maybe sth like this? 
```elixir
  @spec update_tracks_ids(t(), map) :: t()
  def update_tracks_ids(endpoint, mid_to_id) do
    inbound_tracks =
      Map.new(endpoint.inbound_tracks, fn {track_id, track} ->
        new_track_id = Map.get(mid_to_id, track.mid)
        {new_track_id, %Track{track | id: track_id}}
      end)

    %__MODULE__{endpoint | inbound_tracks: inbound_tracks}
  end
  ```

2021-04-29 11:30 UTC, mickel8 commented on lib/membrane_webrtc_plugin/endpoint.ex
> +      |> Map.new(&{&1.id, &1})
But this way we always have to update all inbound tracks so it might not be the best idea. I would leave it as it is but replace Map.values and Enum.map with single Map.new in this way
```elixir
  @spec update_tracks_ids(t(), map) :: t()
  def update_tracks_ids(endpoint, mid_to_id) do
    inbound_tracks =
      endpoint.inbound_tracks
      |> Map.new(fn {track_id, %Track{mid: track_mid}} = track ->
        with %{^track_mid => new_track_id} <- mid_to_id do
          {new_track_id, %Track{track | id: new_track_id}}
        else
          _mid_to_id -> {track_id, track}
        end
      end)

    %__MODULE__{endpoint | inbound_tracks: inbound_tracks}
  end
```

2021-10-13 12:25 UTC, mickel8 commented
outdated

2021-10-13 12:25 UTC, closed without merging