Add creating offer
membraneframework/membrane_webrtc_plugin pull request #3
Opened 2021-02-19 09:42 UTC by mat-hek

moved from #1

2021-02-22 15:51 UTC, mickel8 requested changes

2021-02-22 15:51 UTC, mickel8 commented on lib/membrane_webrtc_plugin/sdp.ex
> +    |> Media.add_attribute(if track.enabled?, do: direction, else: :recvonly)
actually there is mode called `:inactive`. Do we want to use it here instead of `:recvonly`?

2021-02-22 15:51 UTC, mickel8 commented on lib/membrane_webrtc_plugin/sdp.ex
> +  end
```suggestion 
  defp add_extensions(media, :audio, _pt), do: media
```

2021-02-22 15:51 UTC, mickel8 commented on lib/membrane_webrtc_plugin/track.ex
> +defmodule Membrane.WebRTC.Track do
Some docs and specs would be nice

2021-02-22 15:51 UTC, mickel8 commented on lib/membrane_webrtc_plugin/sdp.ex
> +  end
```suggestion
  defp add_codecs(media, codecs), do:
    Enum.reduce(codecs, media, fn attr, media -> Media.add_attribute(media, attr) end)
 ```

2021-02-22 15:51 UTC, mickel8 commented on lib/membrane_webrtc_plugin/sdp.ex
> +    end)
Acctually RTPMapping has payload_type as mandatory key so we probably don't need the second pattern. I would raise instead - we don't want to accept custom codecs without specified payload type. 

Also if codec follows this typespec then we need to adjust pattern matching
` @type codec :: {encoding_name :: atom(), RTPMapping.t() | {RTPMapping.t(), Fmtp.t()}}`

2021-02-22 16:18 UTC, mat-hek commented on lib/membrane_webrtc_plugin/sdp.ex
> +  def create_offer(opts) do
Sure, docs and specs are yet to be added.
> Also, should we append ! to the function name (create_offer!)?

why should we do that?

2021-02-22 16:34 UTC, mat-hek commented on lib/membrane_webrtc_plugin/sdp.ex
> +        get_tracks_data(outbound_tracks, :sendonly)
I think renaming to `tracks` would make this misleading, as it would suggest we just have a collection of tracks there. I don't think `add_tracks_data` is more precise than `add_tracks`, as we add tracks basing on tracks_data. Though I think I get your point, I'll try to think out something.

Regarding `sendrecv`, I'm not sure how that helps, despite saving a few lines of SDP, but it seems other SFUs use that. Personally, I'd like to avoid that if possible.

2021-02-22 16:46 UTC, mat-hek commented on lib/membrane_webrtc_plugin/sdp.ex
> +    end)
The second pattern is for attributes other than RTPMapping, such as FMTP. I haven't updated the typespecs yet.

2021-02-24 11:21 UTC, mickel8 commented on lib/membrane_webrtc_plugin/sdp.ex
> +        get_tracks_data(outbound_tracks, :sendonly)
> as we add tracks basing on tracks_data. Though I think I get your point, I'll try to think out something.

Yeah, this make sense. Let's leave it as it is. 

> Regarding sendrecv, I'm not sure how that helps, despite saving a few lines of SDP, but it seems other SFUs use that. Personally, I'd like to avoid that if possible.

:+1:

2021-02-24 11:24 UTC, mickel8 commented on lib/membrane_webrtc_plugin/sdp.ex
> +  def create_offer(opts) do
> why should we do that?

`create_offer` invokes `Keyword.fetch!` so I thought we should add `!` to our function too as it can raise :thinking: Or `!` is added only when we explicitly raise i.e. we invoke `raise("...")`

2021-02-24 17:34 UTC, mat-hek commented on lib/membrane_webrtc_plugin/sdp.ex
> +  def create_offer(opts) do
I think adding exclamation makes sense if a function raises (explicitly or not) because of evaluating the business logic it implements. Most functions raise if passed arguments of invalid type/non-conformant with docs.

2021-02-25 11:04 UTC, mickel8 requested changes

2021-02-25 11:41 UTC, mickel8 approved these changes

2021-02-25 13:08 UTC, merged