Webrtc client send offer
membraneframework/membrane_webrtc_plugin pull request #32
Opened 2021-08-03 15:28 UTC by Rados13

#10

2021-08-06 09:08 UTC, mat-hek requested changes

2021-08-06 09:08 UTC, mat-hek commented on lib/membrane_webrtc_plugin/endpoint_bin.ex
> +      Map.values(state.inbound_tracks) |> Enum.reduce([], &(&2 ++ [&1.ssrc])) |> List.flatten()
can't we use track ids for the comparison?

2021-08-06 09:08 UTC, mat-hek commented on lib/membrane_webrtc_plugin/endpoint_bin.ex
> +      for mapping <- Map.values(state.mappings), mapping.track_id == track_id, do: mapping
let's just store the mappings as a list, as we have to iterate over it anyway

2021-08-09 08:48 UTC, Rados13 commented on lib/membrane_webrtc_plugin/endpoint_bin.ex
> +      Map.values(state.inbound_tracks) |> Enum.reduce([], &(&2 ++ [&1.ssrc])) |> List.flatten()
Track id is generated during create Track struct, if we don't pass it as opts and we can't pass it because we don't it in SDP offer from client, so during renegotiation they will be always different

2021-08-11 08:32 UTC, mat-hek requested changes

2021-08-31 08:11 UTC, closed without merging

2021-09-02 07:13 UTC, mickel8 commented
Moved to #36