Webrtc client send offer
membraneframework/membrane_webrtc_plugin pull request #36
Opened 2021-08-31 10:59 UTC by Rados13

#32

2021-09-03 08:59 UTC, mat-hek requested changes

2021-09-03 08:59 UTC, mat-hek commented on lib/membrane_webrtc_plugin/sdp.ex
> +        codecs
As we discussed, this never happens. Let's try to consider the user codecs, possibly configuring H264 that way too

2021-09-03 16:40 UTC, mickel8 requested changes

2021-09-03 16:40 UTC, mickel8 commented on lib/membrane_webrtc_plugin/endpoint_bin.ex
> +  def handle_other({:signal, {:sdp_offer, sdp}}, _ctx, state) do
Things that happen here are quite complicated. There are a lot of maps which format is not well defined. Also, functions don't return things that someone can expect they will return basing on their names.

E.g. `get_inbound_tracks_from_sdp` doesn't return only `inbound_tracks` but also `mappings`.
`get_inbound_tracks_from_sdp` calls `SDP.create_track_from_sdp_media` which then calls `get_mapping_from_sdp_media` and this calls `get_mid_type_mappings_from_sdp_media`. 

I would propose following solution
1. Extend Track struct so it can store many RTPMappings
2. Convert sdp m line to Tracks
3. Iterate over Tracks and decide which we are able to handle. Set Tracks that we are not able to handle as inactive.
4. Create answer basing on Track structs

2021-09-03 16:40 UTC, mickel8 commented on lib/membrane_webrtc_plugin/sdp.ex
> +    fmtp_mappings = for %FMTP{} = fmtp_mapping <- sdp_media.attributes, do: fmtp_mapping
There is function called `get_attributes` where you can pass `:rtp_mapping` atom and you should get list of RTPMapping structs.

2021-09-03 16:40 UTC, mickel8 commented on lib/membrane_webrtc_plugin/track.ex
> +          ready?: boolean()
It's not intuitive what `ready?` means. I think we should add some docs for it

2021-09-06 08:18 UTC, Rados13 commented on lib/membrane_webrtc_plugin/sdp.ex
> +    fmtp_mappings = for %FMTP{} = fmtp_mapping <- sdp_media.attributes, do: fmtp_mapping
There is only function called get_attribute which return one element

2021-09-06 08:27 UTC, mat-hek commented on lib/membrane_webrtc_plugin/endpoint_bin.ex
> +  def handle_other({:signal, {:sdp_offer, sdp}}, _ctx, state) do
Good point. The only thing I'd suggest would be to have `SDP.get_tracks` and `SDP.add_tracks`

2021-09-14 08:45 UTC, mat-hek requested changes

2021-09-14 08:45 UTC, mat-hek commented on lib/membrane_webrtc_plugin/endpoint_bin.ex
> +    state = Map.update(state, :outbound_tracks, %{}, &Map.merge(&1, updated_outbound_tracks))
```suggestion
    state = Map.update!(state, :outbound_tracks, &Map.merge(&1, updated_outbound_tracks))
```

2021-09-14 08:45 UTC, mat-hek commented on lib/membrane_webrtc_plugin/endpoint_bin.ex
> +    do: Map.new(tracks, fn track -> {track.id, track.mid} end)
this is a bit overkill, let's move it where it's used

2021-09-14 08:45 UTC, mat-hek commented on lib/membrane_webrtc_plugin/sdp.ex
> +  def get_tracks(sdp, filter_codecs) do
This doesn't return all tracks, but only inbound ones. However, it could return all tracks - we could pass here current outbound tracks and get back inbound tracks and updated outbound tracks - with updated RTP mappings. That way we wouldn't have to expose `update_mapping_and_mid_for_track` and `get_recvonly_medias_mappings` and could take some SDP logic from endpoint bin

2021-09-14 08:45 UTC, mat-hek commented on lib/membrane_webrtc_plugin/sdp.ex
> +  def get_recvonly_medias_mappings(sdp, filter_codecs) do
media is already a plurar form ;)

2021-09-14 08:45 UTC, mat-hek commented on lib/membrane_webrtc_plugin/sdp.ex
> +  def create_track_from_sdp_media(sdp_media, stream_id, filter_codecs) do
this can be private

2021-09-14 08:45 UTC, mat-hek commented on lib/membrane_webrtc_plugin/track.ex
> +          status: :none | :ready | :linked | :disabled,
I'd change `:none` to something like `:pending`

2021-09-14 09:35 UTC, Rados13 commented on lib/membrane_webrtc_plugin/endpoint_bin.ex
> +      else: old_inbound_tracks
It could be problematic because new tracks from sdp would have different track_id and stream_id.

2021-09-15 12:42 UTC, mat-hek requested changes

2021-09-15 12:42 UTC, mat-hek commented on lib/membrane_webrtc_plugin/sdp.ex
> +    rtp_fmtp_pairs = Enum.map(rtp_mappings, &{&1, Map.get(pt_to_fmtp, &1.payload_type)})
```suggestion
    rtp_fmtp_pairs = Enum.map(rtp_mappings, &{&1, Map.fetch!(pt_to_fmtp, &1.payload_type)})
```

2021-09-15 12:42 UTC, mat-hek commented on lib/membrane_webrtc_plugin/sdp.ex
> +    new_rtp_fmtp_pairs = Enum.filter(rtp_fmtp_pairs, &filter_codecs.(&1))
```suggestion
    new_rtp_fmtp_pairs = Enum.filter(rtp_fmtp_pairs, filter_codecs)
```

2021-09-15 12:42 UTC, mat-hek commented on lib/membrane_webrtc_plugin/sdp.ex
> +      %{rtp_fmtp_mappings: rtp_fmtp_pairs, mid: mid, media_type: media_type, disabled?: true}
raise here for now

2021-09-15 12:42 UTC, mat-hek commented on lib/membrane_webrtc_plugin/sdp.ex
> +        |> Media.add_attribute("extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level vad=on")
```suggestion
       Media.add_attribute(media, "extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level vad=on")
```

2021-09-15 12:42 UTC, mat-hek commented on lib/membrane_webrtc_plugin/sdp.ex
> +    outbound_tracks = Keyword.fetch!(opts, :outbound_tracks) |> Enum.sort_by(& &1.timestamp)
not sure if this sorting (and the timestamp field) is needed anymore

2021-09-15 12:42 UTC, mat-hek commented on lib/membrane_webrtc_plugin/sdp.ex
> +    ExSDP.add_media(sdp, tracks)
```suggestion
    inbound_media = Enum.map(inbound_tracks, &create_sdp_media(&1, :recvonly, config))
    outbound_media = Enum.map(outbound_tracks, &create_sdp_media(&1, :sendonly, config))
    media = Enum.sort_by(inbound_media ++ outbound_media, &String.to_integer(&1.attributes[:mid]))
    ExSDP.add_media(sdp, media)
```

2021-09-15 12:42 UTC, mat-hek commented on lib/membrane_webrtc_plugin/sdp.ex
> +  defp update_outbound_tracks_by_type(medias, tracks, type) do
These media are not SDP.Media, let's call them somehow else, like `media_data`. Please check also in other places

2021-09-15 14:24 UTC, mat-hek requested changes

2021-09-15 14:24 UTC, mat-hek commented on lib/membrane_webrtc_plugin/endpoint_bin.ex
>                  spec: ({RTPMapping, FMTP} -> boolean()),
```suggestion
                spec: ({RTPMapping.t, FMTP.t | nil} -> boolean()),
```

2021-09-15 14:24 UTC, mat-hek commented on lib/membrane_webrtc_plugin/sdp.ex
> +    mids = Enum.map(inbound_tracks ++ outbound_tracks, & &1.mid) |> Enum.sort()
mids are strings, they won't be sorted correctly. I'm not sure if they have to be ordered anyway

2021-09-15 14:35 UTC, Rados13 commented on lib/membrane_webrtc_plugin/sdp.ex
> +    mids = Enum.map(inbound_tracks ++ outbound_tracks, & &1.mid) |> Enum.sort()
Yes I forgot that they will be strings. They have to be ordered because SDP group attribute require them in same order as they were given in SDP offer

2021-09-15 14:40 UTC, mat-hek requested changes

2021-09-15 14:40 UTC, mat-hek commented on lib/membrane_webrtc_plugin/sdp.ex
> +    sort_mid = &if &1.mid != nil, do: Integer.parse(&1.mid), else: nil
use String.to_integer - it raises when the conversion cannot succeed

2021-09-16 08:04 UTC, mat-hek approved these changes

2021-09-16 08:04 UTC, mat-hek commented on lib/membrane_webrtc_plugin/sdp.ex
> +      |> Enum.sort_by(&String.to_integer(&1))
```suggestion
      |> Enum.sort_by(&String.to_integer/1)
```

2021-09-16 08:48 UTC, merged