Added handle signal to restart_ice
membraneframework/membrane_webrtc_plugin pull request #38
Opened 2021-09-16 14:55 UTC by Rados13

2021-09-17 09:52 UTC, mat-hek approved these changes

2021-09-23 13:08 UTC, mickel8 requested changes

2021-09-23 13:08 UTC, mickel8 commented on lib/membrane_webrtc_plugin/track.ex
> +  @type id :: {String.t(), String.t()}
Are you sure?

2021-09-23 13:08 UTC, mickel8 commented on lib/membrane_webrtc_plugin/endpoint_bin.ex
> +    types_occurences = %{
Maybe `media_count`?

2021-09-23 13:08 UTC, mickel8 commented on lib/membrane_webrtc_plugin/sdp.ex
> +  def get_tracks(sdp, codecs_filter, old_inbound_tracks, outbound_tracks, peer_id) do
We should use one name in all places. I would opt for `endpoint_id` instead of `peer_id`. Please check other places too

2021-09-23 13:08 UTC, mickel8 commented on lib/membrane_webrtc_plugin/endpoint_bin.ex
> +                description: "Endpoint id"
We should elaborate what this id is used for. E.g.  
```
Endpoint id. It is used for creating Track id.
```

2021-09-23 13:45 UTC, merged