Declare and enable extensions only when applicable
membraneframework/membrane_webrtc_plugin pull request #56
Opened 2021-11-29 12:01 UTC by balins

The proposed flow is:
- on `EndpointBin` initialization, we get a list of modules implementing `Membrane.WebRTC.Extension` behaviour
- when we receive an SDP offer and want to create our representation of a track, we filter extmaps from SDP leaving only the ones that are supported by extensions passed to `EndpointBin`
- when creating an SDP answer we use only these filtered extensions
- when adding input pads to `RTP.SessionBin` we pass only RTP extensions that are supported both by us and the client
- when adding output pads  to `RTP.SessionBin` we pass extension mappings from an atom being an extension name and an identifier proposed by client in extmap, so that when serializing RTP Packet, RTP plugin will be able to remap extension names to integer identifiers individually, based on what was proposed by the stream receiver

2021-11-29 13:38 UTC, Rados13 commented on lib/membrane_webrtc_plugin/endpoint_bin.ex
> +      |> Enum.into(%{})
I think this would look better like this
```elixir
rtp_extension_mapping = 
 Map.new(extmaps, &Extension.as_rtp_mapping(state.extensions,&1))
```

2021-11-29 13:38 UTC, Rados13 commented on lib/membrane_webrtc_plugin/endpoint_bin.ex
> +    ]
So we are removing support for packet_filters?

2021-11-29 14:32 UTC, balins commented on lib/membrane_webrtc_plugin/endpoint_bin.ex
> +    ]
No, on RTP plugin level we are rephrasing  `extensions` as `rtp_extensions`, that is something that is being negotiated via SDP and has its header extension in RTP packets. `packet_filters` on the other hand are becoming general-purpose `extensions`, that on RTC engine level can be applied to tracks with specific encoding (like packet filters), but specifying encoding as `:any` will enable adding extensions regardless of encoding.

2021-11-29 16:46 UTC, Qizot requested changes

2021-11-29 16:46 UTC, Qizot commented on lib/membrane_webrtc_plugin/endpoint_bin.ex
> +  @type enable_track_message :: {:enable_track, Track.id()}
Funny to see that it was that way before :)

2021-11-29 16:46 UTC, Qizot commented on lib/membrane_webrtc_plugin/endpoint_bin.ex
> +        extensions: opts.extensions,
can we name that `rtp_extensions`?

2021-11-29 16:46 UTC, Qizot commented on lib/membrane_webrtc_plugin/extension.ex
> +defmodule Membrane.WebRTC.Extension do
I really enjoy how clean this code here is :)

2021-11-29 16:46 UTC, Qizot commented on lib/membrane_webrtc_plugin/extension/twcc.ex
> +      media
Can you change it to `do/end`? This is a little bit too long for `do:` syntax (to be honest, `do:` should be only used for really short  expressions).

2021-11-29 16:46 UTC, Qizot commented on lib/membrane_webrtc_plugin/sdp.ex
> +          enabled_extensions :: [Extension.t()],
again, I would add the `_rtp_` infix, so we don't get confused at some point.

2021-11-29 16:46 UTC, Qizot commented on mix.exs
> +      {:ex_sdp, github: "membraneframework/ex_sdp"},
At this point we probably have to get this merged as soon as possible (I mean publishing the `ex_sdp`)... To many places where we have to use that. @Rados13 can you do it or anybody who introduced the chrome fix?

2021-11-30 08:08 UTC, balins commented on lib/membrane_webrtc_plugin/endpoint_bin.ex
> +        extensions: opts.extensions,
I was thinking about it, but on the other hand they're not bare `rtp_extensions`, but modules that handle SDP negotiation of extensions AND provide "bare" modules implementing them on RTP level. So I'd rather call them `webrtc_extensions` (and my plan was to use that term in RTC engine). As this is `webrtc_plugin` I thought referring to them like that here will be redundant. Also, general `extensions` are used only when adding output pads, so they do not appear in code too often.

2021-11-30 13:39 UTC, Rados13 commented on lib/membrane_webrtc_plugin/extension/twcc.ex
> +  end
What do you think about this type of change?
```elixir
Media.add_attributes(media, [%Extmap{id: id, uri: @uri, direction: :recvonly} | Enum.map(payload_types, &"rtcp-fb:#{&1} transport-cc")] 
```

2021-11-30 13:51 UTC, balins commented on lib/membrane_webrtc_plugin/extension/twcc.ex
> +  end
I think you're doing too much at once 😛 
It's very concise, but it would argue if it's more readable

2021-11-30 14:23 UTC, Rados13 approved these changes

2021-11-30 15:56 UTC, Qizot commented on lib/membrane_webrtc_plugin/endpoint_bin.ex
> +        extensions: opts.extensions,
It is up to you :)

2021-11-30 15:56 UTC, Qizot approved these changes

2021-12-02 08:50 UTC, merged