Added naive support for simulcast
membraneframework/membrane_webrtc_plugin pull request #58
Opened 2021-12-07 15:19 UTC by Rados13

2021-12-08 12:15 UTC, balins requested changes

2021-12-09 10:40 UTC, balins requested changes
I am a concerned about these `nil`s flying around. Could we do something to better express our intentions when using it for access/filtering/branching etc.?

2021-12-09 10:40 UTC, balins commented on lib/membrane_webrtc_plugin/endpoint_bin.ex
> +    new_tracks = Enum.filter(new_tracks, &(&1.ssrc != nil))
Does this `nil` SSRC indicate a simulcast track?

2021-12-09 10:40 UTC, balins commented on lib/membrane_webrtc_plugin/sdp.ex
> +    |> Media.add_attribute("simulcast:recv #{rids}")
```suggestion
    track.rid
    |> Enum.reduce(media, fn rid, media ->
      Media.add_attribute(media, "rid:#{rid} recv")
    end)
    |> Media.add_attribute("simulcast:recv #{rids}")
```

2021-12-09 10:40 UTC, balins commented on lib/membrane_webrtc_plugin/sdp.ex
> +      end)
We should use parentheses event if function takes 0 arguments or 1 in case of pipe [(guide)](https://github.com/christopheradams/elixir_style_guide/blob/master/README.md#function-calls-and-parentheses)
```suggestion
    rids =
      sdp_media
      |> Media.get_attributes("rid")
      |> Enum.map(fn {_attr, rid} ->
        rid |> String.split(" ", parts: 2) |> hd()
      end)
```

2021-12-09 10:40 UTC, balins commented on lib/membrane_webrtc_plugin/endpoint_bin.ex
> +      |> Map.new(&Extension.as_rtp_mapping(state.extensions, &1))
We should avoid piping only once

```suggestion
    rtp_extension_mapping = Map.new(extmaps, &Extension.as_rtp_mapping(state.extensions, &1))
```

2021-12-09 11:59 UTC, Rados13 commented on lib/membrane_webrtc_plugin/endpoint_bin.ex
> +    new_tracks = Enum.filter(new_tracks, &(&1.ssrc != nil))
It represents the prototype for simulcast tracks. Because at the moment of handling SDP offer we don't know the SSRC of simulcast. So after we receive notification `:new_rtp_stream` with SSRC which we didn't know we create a new simulcast track based on this prototype track. But it can't leave EndpointBin because it didn't represent any media in reality.

2021-12-10 11:58 UTC, balins requested changes
Almost there :) Two last things:
- typespec in `Track.t` and `Track.new` should be updated as `:ssrc` can now be `:simulcast`
- I think we should use plural `:rids` as key in `%Track{}`. Now we are passing `:rids` as track option when using `Track.new`, but then its changed to singular `:rid`. Using plural everywhere would be a clear sign that this is a collection, not a scalar value.

2021-12-13 08:49 UTC, balins approved these changes

2021-12-28 09:44 UTC, mickel8 reviewed
As we dissucussed I can see one problem here and one think we can potentially improve
* we support only one simulcast track
* MAYBE we could benefit from using one struct Track for representing one m-line, even when it's simulcast

Regarding `ssrc_to_track_id`, maybe we could have one key `nil` under which there would be a list of tracks that does not have ssrc? In such a cast simulcast track would have ssrc `nil`

2021-12-28 09:44 UTC, mickel8 commented on lib/membrane_webrtc_plugin/sdp.ex
> +    ssrc = if ssrc == nil, do: :simulcast, else: ssrc.id
I am not sure if that is always true :thinking: 
I think there can be a track which does not have ssrc and it's not a simulcast track.
As an example, offerer can declare it is willing to receive one audio track but it will not assign to it any ssrc as it's answerer responsibility

2021-12-28 09:44 UTC, mickel8 commented on lib/membrane_webrtc_plugin/sdp.ex
> +  @spec remove_simulcast_tracks(inbound_tracks :: [Track.t()]) :: [Track.t()]
We should provide documentation for public functions. Also, I am not sure if this specific function should be a part of public API. It looks like a utility function

Please take a look at other functions too

2021-12-28 10:36 UTC, Rados13 commented on lib/membrane_webrtc_plugin/extension/mid.ex
> +  @moduledoc false
All of the extensions aren't public, but probably as it is options it should be.

2021-12-28 11:06 UTC, Rados13 commented on lib/membrane_webrtc_plugin/sdp.ex
> +  defp add_ssrc(media, %Track{ssrc: :simulcast} = track) do
We remove `defp add_ssrc(media, %Track{ssrc: nil}), do: media`, because now situation, when not simulcast track, doesn't contain SSRC means that some errors occur.

2021-12-28 11:08 UTC, Rados13 commented on lib/membrane_webrtc_plugin/sdp.ex
> +      "extmap-allow-mixed"
This extension mixes two-byte-header extensions with one-byte-header extensions. We don't support a two-byte-header extension, so I don't know why this is here added. It will remove it.

2021-12-28 11:20 UTC, Rados13 commented on lib/membrane_webrtc_plugin/sdp.ex
> +    ssrc = if ssrc == nil, do: :simulcast, else: ssrc.id
Yes but the offerer declares what type and how many tracks he want to receive based on `:offer_data` message. Therefore all for each declared by offerer track to receive we can assign one track from `outbound_tracks` and all tracks in `outbound_tracks` must have SSRC. Also, we didn't allow that SSRC will be nil in typespec of `Track`.

2021-12-28 11:37 UTC, mickel8 commented on lib/membrane_webrtc_plugin/extension/mid.ex
> +  @moduledoc false
Yeap, let's do this in this PR

2021-12-28 11:40 UTC, Rados13 commented on lib/membrane_webrtc_plugin/sdp.ex
> +  @spec remove_simulcast_tracks(inbound_tracks :: [Track.t()]) :: [Track.t()]
We use this function also w EndpointBin module, but I can create Utils module and move this function and some others there?

2021-12-28 11:41 UTC, mickel8 commented on lib/membrane_webrtc_plugin/sdp.ex
> +    ssrc = if ssrc == nil, do: :simulcast, else: ssrc.id
Ok, can we leave comment what is our logic here?

2021-12-28 11:43 UTC, mickel8 commented on lib/membrane_webrtc_plugin/sdp.ex
> +  @spec remove_simulcast_tracks(inbound_tracks :: [Track.t()]) :: [Track.t()]
It looks more like Utils I think. Also, maybe let's call it `filter_simulcast_tracks`? And remember about docs

2021-12-30 11:30 UTC, mickel8 requested changes

2021-12-30 11:30 UTC, mickel8 commented on lib/membrane_webrtc_plugin/sdp.ex
> +  Create simulcast track based on prototype track, rtp header extenstions, and EndpointBin extensions.
```suggestion
  Creates simulcast track based on prototype track, rtp header extenstions, and EndpointBin extensions.
```  
Please checke other functions too

Also I am not sure if these are `EndpointBin extensions`. Aren't they RTP header extensions?

2021-12-30 11:30 UTC, mickel8 commented on lib/membrane_webrtc_plugin/sdp.ex
> +  and list of all outbound_tracks
```suggestion
  Returns how tracks have changed based on SDP offer.

  Function returns four-element tuple, which contains list of new tracks, list of removed tracks, list of all inbound tracks
  and list of all outbound tracks
```

2021-12-30 11:30 UTC, mickel8 commented on lib/membrane_webrtc_plugin/sdp.ex
> +  Default value for filter_codecs option in EndpointBin.
Membrane.WebRTC.EndpointBin - check if that links correctly in docs

2022-01-03 07:23 UTC, Rados13 commented on lib/membrane_webrtc_plugin/sdp.ex
> +  Create simulcast track based on prototype track, rtp header extenstions, and EndpointBin extensions.
Yeah, this is a little bit tricky to distinguish. Because the second parameter of the function is RTP header extensions, which we took from RTP packets, but the third parameter is modules which we pass as an option to EndpointBin and they are standardizing the way we handle RTP header extensions. So using the same words for describing two different parameters would be confusing. That's why I decide to use the name from the description of this opts in EndpointBin.

2022-01-03 15:16 UTC, mickel8 approved these changes

2022-01-04 07:24 UTC, merged