Update outbound tracks extmaps
membraneframework/membrane_webrtc_plugin pull request #65
Opened 2022-01-04 12:07 UTC by Rados13

This PR fix printing warns in the browser console that we send extensions with id, which isn't negotiated in SDP. This situation occurs because we didn't update the `extmaps` attribute in outbound tracks structs for each EndpointBin. So an example situation, the first peer (Chrome browser) declares that it will send a VAD extension with id 1 in his track. All other EndpointBins receive buffers of this track. But another peer can have declared a VAD extension with id 14 in his SDP negotiation like Safari does. To avoid this situation in function `update_mapping_and_mid_for_track` we update the `extmaps` attribute for this track to have proper attributes.

2022-01-07 13:37 UTC, balins requested changes

2022-01-07 13:37 UTC, balins commented on lib/membrane_webrtc_plugin/sdp.ex
> +          Enum.any?(track.extmaps, &(&1.uri == extmap.uri))
Also AFAIK these extmaps are already being filtered when they get added to a `%Track{}`

2022-01-10 09:27 UTC, Rados13 commented on lib/membrane_webrtc_plugin/sdp.ex
> +          Enum.any?(track.extmaps, &(&1.uri == extmap.uri))
But it filters it in different endpoint and we have to do the same in another endpoint.

2022-01-10 09:49 UTC, balins commented on lib/membrane_webrtc_plugin/sdp.ex
> +          Enum.any?(track.extmaps, &(&1.uri == extmap.uri))
OK, what with `Extension.supported?/3`?

2022-01-10 10:14 UTC, Rados13 commented on lib/membrane_webrtc_plugin/sdp.ex
> +          Enum.any?(track.extmaps, &(&1.uri == extmap.uri))
We can't use it, because both extmaps are struct from SDP, not Extension modules.

2022-01-10 11:52 UTC, balins commented on lib/membrane_webrtc_plugin/sdp.ex
> +          Enum.any?(track.extmaps, &(&1.uri == extmap.uri))
Shouldn't this function have also `extensions` of Endpoint as an argument? Simply checking the `uri` may not be sufficient to determine if an extmap is supported for given track.

2022-01-11 08:33 UTC, balins approved these changes

2022-01-11 08:57 UTC, merged