Make extensions rtp_module configurable
membraneframework/membrane_webrtc_plugin pull request #66
Opened 2022-01-18 17:06 UTC by Rados13

2022-01-20 08:39 UTC, balins requested changes

2022-01-20 08:39 UTC, balins commented on lib/membrane_webrtc_plugin/extension/vad.ex
> +    Map.merge(%@rtp_module{vad_id: vad_id}, rtp_opts)
```suggestion
    struct!(@rtp_module, [vad_id: vad_id | rtp_opts])
```

2022-01-20 08:39 UTC, balins commented on lib/membrane_webrtc_plugin/extension.ex
> +            rtp_opts: Keyword.new()
```suggestion
  @enforce_keys [:module]
  defstruct @enforce_keys ++ [rtp_opts: Keyword.new()]
```

2022-01-20 08:39 UTC, balins commented on lib/membrane_webrtc_plugin/extension.ex
> +  Create a `__MODULE__` struct for specific extension.
```suggestion
  Creates a `#{inspect(__MODULE__)}` struct for a specific extension.
```

2022-01-20 08:50 UTC, balins commented
It don't think it needs to be included in this PR, but at some point we should revisit if it would be beneficial to replace some callbacks with additional fields in `%WebRTC.Extension{}` struct (e.g. `uri`) and try to handle as much as possible in base `WebRTC.Extension` module. This approach could help us mitigate repeating code among all modules implementing `WebRTC.Extension`.

2022-01-20 16:36 UTC, mickel8 requested changes

2022-01-20 16:36 UTC, mickel8 commented on lib/membrane_webrtc_plugin/extension.ex
> +        }
We need docs here. Also, we need better type for `rtp_opts`

2022-01-25 09:09 UTC, Rados13 commented on lib/membrane_webrtc_plugin/extension.ex
> +        }
I am not sure if we can specify here a better description for rtp_opts, as every RTP module has its own options.

2022-01-27 10:37 UTC, mickel8 commented on lib/membrane_webrtc_plugin/extension.ex
> +    * name - an atom identifying the extension in `Membrane.RTP.SessionBin`
Put this as doc for type `t` i.e.
```elixir
@typedoc """
...
''''
@type t :: %__MODULE__{
```

2022-01-27 10:38 UTC, mickel8 approved these changes

2022-01-27 15:40 UTC, balins approved these changes
Just a suggestion, we can also consider mapping extension modules like 
```extensions:  Enum.map(opts.extensions, &(if is_struct(&1), do: &1, else: &1.new()))```
in `WebRTC.EndpointBin.handle_init/1` to avoid passing lists like `[TWCC.new(), Mid.new(), Rid.new()]` when we don't want to customize extensions.

2022-02-08 08:31 UTC, merged