Voic activity detection (vad) based on `audio_level` in RTP header
membraneframework/membrane_webrtc_plugin pull request #7
Opened 2021-03-26 15:25 UTC by mickel8

2021-03-29 15:27 UTC, mat-hek requested changes

2021-03-29 15:27 UTC, mat-hek commented on lib/membrane_webrtc_plugin/endpoint_bin.ex
> +  require Logger
is that needed?

2021-03-30 08:27 UTC, mickel8 commented on lib/membrane_webrtc_plugin/rtp_vad.ex
> +  notification `{:vad, false}`.
Why do we want to measure time? By measuring time we mean taking avg of audio level from packiets in last `x` ms?

2021-03-30 09:24 UTC, mat-hek commented on lib/membrane_webrtc_plugin/rtp_vad.ex
> +  notification `{:vad, false}`.
> By measuring time we mean taking avg of audio level from packiets in last x ms?

Exactly.

> Why do we want to measure time? 

Well, why do we want to measure packets? :P Setting VAD to true/active when someone speaks for X ms seems reasonable.

2021-03-31 09:02 UTC, mickel8 commented on lib/membrane_webrtc_plugin/rtp_vad.ex
> +  defp get_time(), do: System.monotonic_time(:millisecond)
Would be relaying on RTP packets' timestamps even better?

2021-03-31 09:03 UTC, mickel8 commented on lib/membrane_webrtc_plugin/rtp_vad.ex
> +defmodule Membrane.RTPVAD do
I will do this after accepting changes related to the current comments so that we know what has been changed

2021-04-01 13:17 UTC, mat-hek requested changes

2021-04-01 13:17 UTC, mat-hek commented on lib/membrane_webrtc_plugin/rtp_vad.ex
> +                """
what does that give us?

2021-04-01 13:17 UTC, mat-hek commented on lib/membrane_webrtc_plugin/rtp_vad.ex
> +    end
Lot's of conditions here. Can we simplify it?

2021-04-01 13:17 UTC, mat-hek commented on lib/membrane_webrtc_plugin/rtp_vad.ex
> +    Enum.reduce(list, 0, fn {level, _timestamp}, acc -> level + acc end) / length(list)
Either do that in constant time or use Enum.sum and Enum.count

2021-04-01 13:17 UTC, mat-hek commented on lib/membrane_webrtc_plugin/rtp_vad.ex
> +      [notify: {:vad, new_vad}]
won't it send notification every handled buffer in these cases?

2021-04-01 13:30 UTC, mickel8 commented on lib/membrane_webrtc_plugin/rtp_vad.ex
> +                """
This will handle cases when in last x ms we have small number of packets (especially situation when we have only one packet in last x ms) and their audio levels suggest speech activity. In such cases we might not want to emit notification about speech.

2021-04-01 13:38 UTC, mickel8 commented on lib/membrane_webrtc_plugin/rtp_vad.ex
> +                """
It might not be a good idea to decide about speech basing on 1-10 packets. There can be e.g. connection issues and we might get only singular packets with speech activity or we can have situation like this
f f f f f f f f f f f f f f... f  
| __ time window __ |

f f f f f f f f f f f f f... f t 
..............................|__ time window __ |
                                 
and here we will detect speech

because only new packet is in range of time window and it indicates speech

2021-04-01 13:41 UTC, mickel8 commented on lib/membrane_webrtc_plugin/rtp_vad.ex
> +      [notify: {:vad, new_vad}]
This will notify only when changing state. If we are already in `:silence` or `:speech` and new buffer doesn't change this state we will do nothing

2021-04-01 13:42 UTC, mat-hek commented on lib/membrane_webrtc_plugin/rtp_vad.ex
> +                """
ok, so instead of filling the queue with silence I'd just assume there's no speech if we don't have enough data

2021-04-01 13:45 UTC, mat-hek commented on lib/membrane_webrtc_plugin/rtp_vad.ex
> +      [notify: {:vad, new_vad}]
👍  haven't caught that

2021-04-01 14:52 UTC, mickel8 commented on lib/membrane_webrtc_plugin/rtp_vad.ex
> +    end
we can do 
```elixir
    cond do
      vad_maybe_silence?(new_vad, state) ->
        Map.merge(state, %{vad: :maybe_silence, vad_silence_timestamp: state.current_timestamp})

      !vad_silence?(new_vad, state) ->
        state

      true ->
        Map.merge(state, %{vad: new_vad})
    end
 ```
 But this way we will update `vad` in state in last clause very often.

2021-04-06 10:50 UTC, mat-hek commented on lib/membrane_webrtc_plugin/rtp_vad.ex
> +    end
That's much better. Without finding the performance bottlenecks, we shouldn't do any optimizations unless they're easy to implement _and_ don't make the code less readable. Especially if they don't improve the computational complexity.

That said, it's still a bit confusing why we don't always update the `vad`, and the `vad` in state is something different from the `vad` obtained from `get_vad`. Maybe we can improve the naming or split the `vad` in state into more parameters?

2021-04-06 13:40 UTC, mickel8 commented on lib/membrane_webrtc_plugin/rtp_vad.ex
> +    end
I have renamed `new_vad` and `get_vad` to `audio_levels_vad` and `get_audio_levels_vad` so now to determine `vad` we have to compare `audio_levels_vad` with `vad` saved in state - `state.vad`.

2021-04-06 14:40 UTC, mickel8 commented on lib/membrane_webrtc_plugin/rtp_vad.ex
> +    end
It turned out that the above `cond` isn't valid in 100% but I have refactored it a little in `membrane_rtp_plugin`

2021-04-07 11:55 UTC, mat-hek approved these changes

2021-04-07 11:57 UTC, merged