Raise instead of disabling a track when simulcast is offered when it's not supported
membraneframework/membrane_webrtc_plugin pull request #92
Opened 2022-07-18 10:43 UTC by daniel-jodlos

2022-07-26 13:32 UTC, mickel8 requested changes

2022-07-26 13:32 UTC, mickel8 commented on lib/membrane_webrtc_plugin/track.ex
> +          raise RuntimeError, message: "Simulcast was offered, but it's not supported"
Please update the comment above and update or remove the log above .

2022-08-04 16:52 UTC, mickel8 approved these changes

2022-08-08 05:26 UTC, daniel-jodlos commented
@mickel8 Do we release this change instantly or wait for something?

2022-08-08 05:26 UTC, merged